### ISSUE TITLE
Rewrite scanner in C

### ISSUE THREAD

**Issue by clason** [savonet/tree-sitter-liquidsoap#1]
Just a small heads-up: tree-sitter has deprecated C++ for external scanners due to portability issues (especially with WASM, which will become a central part of the parser distribution strategy); see https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners. Accordingly, nvim-treesitter will drop support for such parsers in 1.0, too.

In the upcoming release (0.22.0), tree-sitter provides a new `array.h` header for use in scanners, so C++ is no longer necessary just for `<vector>`. Feel free to reach out on https://matrix.to/#/#tree-sitter-chat:matrix.org if you need help with the rewrite!

**Comment by toots** [comment]
Thanks for the heads up! We'll look at it very soon.

**Comment by clason** [comment]
No pressure, but you're the very last remaining C++ scanner parser ;) (And tree-sitter v0.22.0 is released now, so no more reason to wait.)

**Comment by toots** [comment]
@clason thanks for the heads up! What's the status of https://github.com/tree-sitter/tree-sitter/issues/2620? The only reason we use c++ is for the regexp support to supplement for the missing reusable regexp support..

**Comment by clason** [comment]
It's still planned but will have to wait until the next ABI bump (as it will make parsers backward-incompatible). 

I'd still recommend moving to C (there must be regex support there as well; afaik `regex.h` is part of POSIX and not C++ specific) now and then replacing the custom regex with the upstream functions whenever that happens. Maybe @amaanq can help you. C++ scanners _are_ deprecated and _will_ no longer be supported in the near future.

**Comment by clason** [comment]
Actually, I'm not sure the regex support is planned for _scanners_ -- the plan so far only concerns exposing it via the library/crate so that queries can use the `#match?` predicate in an editor-independent way.

As far as I know, yours is the only grammar that wants to use non-trivial regex in their scanner, so I'd assume the enthusiasm is rather limited.

**Comment by toots** [comment]
Sure I understand. We might have to add a vendored dependency in this case. I just imagined that since the unicode logic is already present in the internal code it wouldn't be too hard to expose it? I'll work on this soon.

**Comment by clason** [comment]
I think it makes sense, yes, and it _is_ on the roadmap. But it's a bit harder than just adding a single self-contained array header.

Unfortunately, an external dependency would likely be a deal-breaker for nvim-treesitter (no more custom compile logic). Not sure what the best way forward is. Is unicode regex handling really necessary? Other unicode-aware languages don't seem to need it.

**Comment by toots** [comment]
The reason we have it is because historically, the language supports two types of syntax:
```
def f(x, y)
  "foo"
end
```

and
```
def f
  (x, y)
end
```
Where the latter means that `f` is the variable `(x, y)`.

This is handled by the internal parser by doing a lookahead on variables to know if we're parsing `<variable>` or `<variable>(`.

I wasn't able to make this work in tree-sitter without introducting an external scanner. But, this also calls for a change of syntax for us. I wouldn't be opposed of getting rid of this and making the parser only work with the first case..

**Comment by clason** [comment]
That does sound like a horrible thing to parse ;)

**Comment by toots** [comment]
Ok I forgot I already had found a way to re-use the variable name matching using an external token 😆

The new array API was super helpful too!

**Comment by clason** [comment]
Great! That was the last C++ scanner in nvim-treesitter, this will simplify things a lot (and open up binary distribution via wasm). Thank you!

**Comment by toots** [comment]
Glad to hear. I think `wasm` is gonna be awesome.
